# list
letters = ["a","b","c","d","e","f","g","h","i","j","k","l"]
print("sequential:")
print(letters[0])
print(letters[1])
print(letters[2])
print(letters[3])
print(letters[4])
print(letters[5])
print(letters[6])
print(letters[7])
print(letters[8])
print(letters[9])
print(letters[10])
print(letters[11])
print("reverse:")
print(letters[0])
print(letters[1])
print(letters[2])
print(letters[3])
print(letters[4])
print(letters[5])
print(letters[6])
print(letters[7])
print(letters[8])
print(letters[9])
print(letters[10])
print(letters[11])